language: cpp

os:
  - osx

notifications:
  email: false

before_script:
# travis has changed to 64-bit and we require 32-bit compatibility libraries
  - brew update 
  - brew install i386-elf-gcc
  - export COS_ROOT=`pwd`


script:
  - scons target=$TARGET

env:
  #- TARGET='x86'
