language: cpp

notifications:
  email: false

before_script:
# travis has changed to 64-bit and we require 32-bit compatibility libraries
  - sudo apt-get update
  - "sudo apt-get -qq install clang gcc-multilib libc6:i386 libgcc1:i386 gcc-4.6-base:i386 libstdc++5:i386 libstdc++6:i386 libsdl-dev || true"
  - export COS_ROOT=`pwd`


script:
  - scons target=$TARGET

env:
  - TARGET='x86' COS_CC = '' 
