Import('COS_ROOT')
Import('settings')
from building import *

objs = []
cwd  = GetCurrentDir()
list = os.listdir(cwd)

for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        objs = objs + SConscript(os.path.join(item, 'SConscript'))


CPPPATH = [os.path.join(cwd, 'include')]
group = DefineGroup("test-inc" , [], depend = [''], CPPPATH = CPPPATH)
objs += group

Return('objs')

