Import('COS_ROOT')
Import('settings')
from building import *

cwd  = GetCurrentDir()

src = Glob('*.c') + Glob('*.cpp') + Glob('*.S')
src += Glob('ipc/*.c') + Glob('ipc/*.cpp') + Glob('ipc/*.S')
src += Glob('device/*.c') + Glob('device/*.cpp') + Glob('device/*.S')

CPPPATH = [cwd, COS_ROOT + '/include']
group = DefineGroup('Kernel', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
