Import('COS_ROOT')
Import('settings')
import os
from building import *

objs = []
cwd  = GetCurrentDir()
list = os.listdir(cwd)


objs = SConscript(os.path.join(settings.ARCH, 'SConscript'))

Return('objs')
