Import('settings')
from building import *

cwd = GetCurrentDir()
src = Glob('*.c') + Glob('*.cpp') + Glob('*.S') 
CPPPATH = [cwd]


group = DefineGroup('gui', src, depend = ['CONFIG_GUI'],
                    CPPPATH = CPPPATH)

Return('group')
