Import('COS_ROOT')
Import('settings')
from building import *

cwd  = GetCurrentDir()

src = Glob('*.c') + Glob('*.cpp') + Glob('*.S')

CPPPATH = [cwd]

group = DefineGroup('x86-boot', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
