Import('settings')
from building import *

cwd = GetCurrentDir()
src = Glob('*.c') + Glob('*.cpp') + Glob('*.S') 
CPPPATH = [cwd]


group = DefineGroup('libstl', src, depend = ['CONFIG_STDLIB'],
                    CPPPATH = CPPPATH)

Return('group')
