# for module compiling
import os
from building import *

objs = []
cwd  = GetCurrentDir()
list = os.listdir(cwd)

for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        objs = objs + SConscript(os.path.join(item, 'SConscript'))


src = Glob('*.c') + Glob('*.cpp') + Glob('*.S') 
CPPPATH = [cwd]
group = DefineGroup('runtime', src, depend = [],
                    CPPPATH = CPPPATH)

Return('objs')
