Import('settings')
from building import *

cwd = GetCurrentDir()


src = Glob('*.c') + Glob('*.cpp') + Glob('*.S')


CPPPATH = [cwd]

group = DefineGroup('shell', src, depend = [''],
                    CPPPATH = CPPPATH)

Return('group')
